- name: Update apt cache
  become: true
  ansible.builtin.apt:
    cache_valid_time: "{{ cache_valid_time }}"
    update_cache: true

- name: Upgrade all packages
  become: true
  ansible.builtin.apt:
    upgrade: dist

- name: Reboot instance if necessary
  ansible.builtin.include_tasks:
    file: reboot.yml
