- name: Install packages
  become: true
  with_items: "{{ apt_packages }}"

  ansible.builtin.apt:
    cache_valid_time: "{{ cache_valid_time }}"
    name: "{{ item }}"
    update_cache: true

- name: Check if reboot is required
  changed_when: reboot_required.stat.exists
  notify: Reboot
  register: reboot_required
  ansible.builtin.stat:
    get_checksum: false
    path: /var/run/reboot-required

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Add direnv config to the .bashrc
  ansible.builtin.blockinfile:
    block: |
      eval "$(direnv hook bash)"
    marker: "# {mark} direnv ANSIBLE MANAGED BLOCK"
    path: "{{ ansible_env.HOME }}/.bashrc"
