- name: Clone/update asdf
  git:
    dest: "{{ ansible_env.HOME }}/.asdf"
    repo: https://github.com/asdf-vm/asdf.git
    depth: 1
    version: v{{ asdf_expected }}

- name: Add asdf config to the .bashrc
  blockinfile:
    insertbefore: BOF
    marker: "# {mark} asdf ANSIBLE MANAGED BLOCK"
    block: |
      . $HOME/.asdf/asdf.sh
      . $HOME/.asdf/completions/asdf.bash
    path: "{{ ansible_env.HOME }}/.bashrc"

- name: Install plugins
  register: asdf_plugins_installed
  changed_when: '"already added" not in asdf_plugins_installed.stderr'
  command: "{{ ansible_env.HOME }}/.asdf/bin/asdf plugin-add {{ item }}"
  failed_when: false
  with_items:
    - github-cli https://github.com/bartlomiejdanek/asdf-github-cli.git
    - packer https://github.com/asdf-community/asdf-hashicorp.git
    - terraform https://github.com/asdf-community/asdf-hashicorp.git
    - terragrunt https://github.com/ohmer/asdf-terragrunt
    - terraform-docs https://github.com/looztra/asdf-terraform-docs
    - tflint https://github.com/skyzyx/asdf-tflint
    - sops https://github.com/feniix/asdf-sops.git
