- name: Clone/update asdf
  ansible.builtin.git:
    depth: 1
    dest: "{{ ansible_env.HOME }}/.asdf"
    repo: https://github.com/asdf-vm/asdf.git
    version: v{{ asdf_version }}

- name: Add asdf config to the .bashrc
  ansible.builtin.blockinfile:
    insertbefore: BOF
    marker: "# {mark} asdf ANSIBLE MANAGED BLOCK"
    block: |
      . $HOME/.asdf/asdf.sh
      . $HOME/.asdf/completions/asdf.bash
    path: "{{ ansible_env.HOME }}/.bashrc"

- name: Install plugins
  changed_when: '"already added" not in is_asdf_plugin_installed.stderr'
  failed_when: false
  register: is_asdf_plugin_installed
  with_items: "{{ asdf_plugins }}"
  ansible.builtin.command: "{{ ansible_env.HOME }}/.asdf/bin/asdf plugin-add {{ item.name }} {{ item.repo }}"

- name: Install tools
  changed_when: '"already installed" not in is_asdf_tool_installed.stdout'
  register: is_asdf_tool_installed
  with_items: "{{ asdf_global }}"
  ansible.builtin.shell: |
    {{ ansible_env.HOME }}/.asdf/bin/asdf install {{ item.name }} {{ item.version }}
    {{ ansible_env.HOME }}/.asdf/bin/asdf global {{ item.name }} {{ item.version }}
