- name: Update installed apt packages
  ansible.builtin.include_tasks:
    file: apt-upgrade.yml

- name: Install base apt packages
  ansible.builtin.include_tasks:
    file: apt.yml

- name: Install shell history search
  ansible.builtin.include_tasks:
    file: hstr.yml

- name: Customize bash configuration
  ansible.builtin.include_tasks:
    file: bashrc.yml

- name: Configure SSH
  ansible.builtin.include_tasks:
    file: ssh.yml
