- name: Set more friendly shell hints
  ansible.builtin.blockinfile:
    block: |
      # https://scriptim.github.io/bash-prompt-generator/
      PS1='\[\e[0m\]\u\[\e[0m\]@\[\e[0m\]\h\[\e[0m\]:\[\e[0;38;5;46m\]\w\n\[\e[0m\]└─\[\033[0;32m\]$(__git_ps1)\[\033[0;0m\] \$ '
    marker: "# {mark} shell ANSIBLE MANAGED BLOCK"
    path: "{{ ansible_env.HOME }}/.bashrc"
