- name: Add repository apt key
  become: true
  ansible.builtin.apt_key:
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Add repository to the apt sources
  become: true
  ansible.builtin.apt_repository:
    state: present
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"

- name: Install packages
  become: true
  notify:
    - Restart docker daemon
  with_items:
    - containerd.io
    - docker-buildx-plugin
    - docker-ce
    - docker-ce-cli
    - docker-compose-plugin
  ansible.builtin.apt:
    name: "{{ item }}"

- name: Create docker group
  become: true
  ansible.builtin.group:
    name: docker
    state: present

- name: Add user "{{ ansible_user_id }}" to the docker group
  become: true
  ansible.builtin.user:
    append: true
    groups: docker
    name: "{{ ansible_user_id }}"
