- include: base.yml
  tags:
    - base

- include: docker.yml
  tags:
    - docker

- include: pyenv.yml
  tags:
    - pipx
    - poetry
    - python

- include: pipx.yml
  tags:
    - pipx

- include: poetry.yml
  tags:
    - poetry

- include: packer.yml
  tags:
    - packer

- include: sops.yml
  tags:
    - sops

- include: terraform.yml
  tags:
    - terraform
    - terraform-docs
    - terragrunt
    - tflint

- include: terraform-docs.yml
  tags:
    - terraform-docs

- include: terragrunt.yml
  tags:
    - terragrunt

- include: tflint.yml
  tags:
    - tflint

- include: psql.yml
  tags:
    - psql

- include: asdf.yml
  tags:
    - asdf
