- name: Base setup
  tags:
    - base
  ansible.builtin.include_tasks:
    file: base.yml
    apply:
      tags:
        - base

- name: Add docker
  tags:
    - docker
  ansible.builtin.include_tasks:
    file: docker.yml
    apply:
      tags:
        - docker

- name: Add PostgreSQL
  tags:
    - psql
  ansible.builtin.include_tasks:
    file: psql.yml
    apply:
      tags:
        - psql

- name: Add asdf
  tags:
    - asdf
  ansible.builtin.include_tasks:
    file: asdf.yml
    apply:
      tags:
        - asdf

- name: Add pyenv
  tags:
    - pipx
    - poetry
    - python
  ansible.builtin.include_tasks:
    file: pyenv.yml
    apply:
      tags:
        - pipx
        - poetry
        - python

- name: Add pipx
  tags:
    - pipx
  ansible.builtin.include_tasks:
    file: pipx.yml
    apply:
      tags:
        - pipx

- name: Add poetry
  tags:
    - poetry
  ansible.builtin.include_tasks:
    file: poetry.yml
    apply:
      tags:
        poetry

- name: Add vagrant
  tags:
    - vagrant
  ansible.builtin.include_tasks:
    file: vagrant.yml
    apply:
      tags:
        - vagrant
