- name: Base setup
  ansible.builtin.include_tasks:
    file: base.yml
    apply:
      tags:
        - base
  tags:
    - base

- name: Add Docker
  ansible.builtin.include_tasks:
    file: docker.yml
    apply:
      tags:
        - docker
  tags:
    - docker

- name: Add pyenv
  ansible.builtin.include_tasks:
    file: pyenv.yml
    apply:
      tags:
        - pipx
        - poetry
        - python
  tags:
    - pipx
    - poetry
    - python

- name: Add pipx
  ansible.builtin.include_tasks:
    file: pipx.yml
    apply:
      tags:
        - pipx
  tags:
    - pipx

- name: Add poetry
  ansible.builtin.include_tasks:
    file: poetry.yml
    apply:
      tags:
        poetry
  tags:
    - poetry

- name: Add PostgreSQL client
  ansible.builtin.include_tasks:
    file: psql.yml
    apply:
      tags:
        - psql
  tags:
    - psql

- name: Add asdf
  ansible.builtin.include_tasks:
    file: asdf.yml
    apply:
      tags:
        - asdf
  tags:
    - asdf
