- name: Check pipx existence
  changed_when: "no_pipx.rc != 0"
  failed_when: false
  register: no_pipx
  ansible.builtin.command: "{{ ansible_env.HOME }}/.local/bin/pipx --version"

- name: Install pipx
  when: no_pipx is changed
  ansible.builtin.shell: >
    set -o pipefail &&
    PYENV_ROOT="$HOME/.pyenv" &&
    PATH="$PYENV_ROOT/bin:$PATH" &&
    eval "$(pyenv init --path)"  &&
    eval "$(pyenv init -)" &&
    PYENV_VERSION={{ default_user_python_version }} python -m pip install --user pipx
  args:
    executable: /bin/bash

- name: Add pipx path to the .bashrc
  ansible.builtin.blockinfile:
    block: |
      export PATH="$HOME/.local/bin:$PATH"
    insertbefore: BOF
    marker: "# {mark} .local/bin ANSIBLE MANAGED BLOCK"
    path: "{{ ansible_env.HOME }}/.bashrc"

- name: Install tools
  register: tool_installed
  changed_when: '"already seems to be installed" not in tool_installed.stdout'
  ansible.builtin.command: "{{ ansible_env.HOME }}/.local/bin/pipx install {{ item }}"
  with_items:
    - pre-commit
    - awscli
    - yq
