- name: Check pipx existence
  changed_when: "pipx_version.rc != 0"
  failed_when: false
  notify: Install pipx
  register: pipx_version
  ansible.builtin.command: "{{ ansible_env.HOME }}/.local/bin/pipx --version"

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Add pipx path to the .bashrc
  ansible.builtin.blockinfile:
    block: |
      export PATH="$HOME/.local/bin:$PATH"
    insertbefore: BOF
    marker: "# {mark} .local/bin ANSIBLE MANAGED BLOCK"
    path: "{{ ansible_env.HOME }}/.bashrc"

- name: Install tools
  changed_when: '"already seems to be installed" not in is_pipx_tool_installed.stdout'
  register: is_pipx_tool_installed
  with_items:
    - awscli
    - cookiecutter
    - detect-secrets
    - pre-commit
    - yq
  ansible.builtin.command: "{{ ansible_env.HOME }}/.local/bin/pipx install {{ item }}"
