- name: Check poetry existence
  changed_when: "poetry_version.rc != 0"
  failed_when: false
  register: poetry_version
  notify:
    - Install poetry
    - Configure poetry
  ansible.builtin.command: "{{ ansible_env.HOME }}/.local/bin/poetry -V"

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Add poetry path to the .bashrc
  ansible.builtin.blockinfile:
    block: |
      export PATH="$HOME/.local/bin:$PATH"
    insertbefore: BOF
    marker: "# {mark} .local/bin ANSIBLE MANAGED BLOCK"
    path: "{{ ansible_env.HOME }}/.bashrc"

- name: Update poetry
  changed_when: "'No dependencies to install or update' not in is_poetry_updated.stdout"
  register: is_poetry_updated
  ansible.builtin.command: "{{ ansible_env.HOME }}/.local/bin/poetry self update"
