- name: Add the official PostgreSQL repository to the apt sources
  block:
    - name: Add GPG key
      ansible.builtin.apt_key:
        id: B97B0AFCAA1A47F044F244A07FCC7D46ACCC4CF8
        url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
        state: present

    - name: Add apt source
      become: true
      ansible.builtin.apt_repository:
        repo: "deb http://apt.postgresql.org/pub/repos/apt {{ ansible_distribution_release }}-pgdg main"
        state: present

- name: Install PostgreSQL client
  become: true
  ansible.builtin.apt:
    name: postgresql-client-15
    update_cache: true
