- name: Add the GPG key for the official PostgreSQL repository
  become: true
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: Save the current Ubuntu release version into a variable
  command: lsb_release -cs
  register: ubuntu_version
  changed_when: ubuntu_version.rc != 0

- name: Add the PostgreSQL repository to APT sources
  become: true
  apt_repository:
    repo: deb http://apt.postgresql.org/pub/repos/apt {{ ubuntu_version.stdout }}-pgdg main
    state: present
  register: pg_repository

- name: Install PostgreSQL client
  become: true
  when: pg_repository is changed
  apt:
    name: postgresql-client-14
    update_cache: true
