- name: Install packages for build Python
  become: true
  apt:
    cache_valid_time: "{{ cache_valid_time }}"
    name:
      - build-essential
      - libbz2-dev
      - libffi-dev
      - liblzma-dev
      - libncurses5-dev
      - libncursesw5-dev
      - libreadline-dev
      - libsqlite3-dev
      - libssl-dev
      - llvm
      - python-openssl
      - tk-dev
      - xz-utils
      - zlib1g-dev
    update_cache: true

- name: Clone/update pyenv
  git:
    dest: "{{ ansible_env.HOME }}/.pyenv"
    repo: https://github.com/pyenv/pyenv.git

- name: Check default Python version
  changed_when: (python_version.rc != 0) or
                (default_user_python_version not in python_version.stdout)
  failed_when: false
  register: python_version
  command: "{{ ansible_env.HOME }}/.pyenv/bin/pyenv global"

- name: Install/modify default python for user
  args:
    executable: /bin/bash
  when: python_version is changed
  shell: >
    PYENV_ROOT="$HOME/.pyenv" &&
    PATH="$PYENV_ROOT/bin:$PATH" &&
    eval "$(pyenv init --path)"  &&
    eval "$(pyenv init -)" &&
    pyenv install {{ default_user_python_version }} &&
    pyenv global {{ default_user_python_version }}

- name: Add pyenv config to the .bashrc
  blockinfile:
    insertbefore: BOF
    marker: "# {mark} pyenv ANSIBLE MANAGED BLOCK"
    block: |
      export PYENV_ROOT="$HOME/.pyenv"
      export PATH="$PYENV_ROOT/bin:$PATH"
      eval "$(pyenv init --path)"
      eval "$(pyenv init -)"
    path: "{{ ansible_env.HOME }}/.bashrc"

- name: Change byobu python
  blockinfile:
    marker: "# {mark} byobu python ANSIBLE MANAGED BLOCK"
    block: |
      export BYOBU_PYTHON="$PYENV_ROOT/shims/python"
    path: ~/.bashrc
