- name: Install packages for build Python
  become: true
  with_items:
    - build-essential
    - libbz2-dev
    - libffi-dev
    - liblzma-dev
    - libncurses5-dev
    - libncursesw5-dev
    - libreadline-dev
    - libsqlite3-dev
    - libssl-dev
    - llvm
    - python3-openssl
    - tk-dev
    - xz-utils
    - zlib1g-dev
  ansible.builtin.apt:
    cache_valid_time: "{{ cache_valid_time }}"
    name: "{{ item }}"

- name: Clone/update pyenv
  ansible.builtin.git:
    dest: "{{ ansible_env.HOME }}/.pyenv"
    repo: https://github.com/pyenv/pyenv.git
    version: v{{ pyenv_version }}

- name: Check default Python version
  changed_when: (global_python.rc != 0) or
    (python_version not in global_python.stdout)
  failed_when: false
  notify: Install/modify default Python for user
  register: global_python
  ansible.builtin.command: "{{ ansible_env.HOME }}/.pyenv/bin/pyenv global"

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Add pyenv config to the .bashrc
  ansible.builtin.blockinfile:
    insertbefore: BOF
    marker: "# {mark} pyenv ANSIBLE MANAGED BLOCK"
    block: |
      export PYENV_ROOT="$HOME/.pyenv"
      export PATH="$PYENV_ROOT/bin:$PATH"
      eval "$(pyenv init --path)"
      eval "$(pyenv init -)"
    path: "{{ ansible_env.HOME }}/.bashrc"

- name: Change byobu python
  ansible.builtin.blockinfile:
    marker: "# {mark} byobu Python ANSIBLE MANAGED BLOCK"
    block: |
      export BYOBU_PYTHON="$PYENV_ROOT/shims/python"
    path: ~/.bashrc
