- name: Create client config file if not exists
  ansible.builtin.file:
    access_time: preserve
    mode: "600"
    modification_time: preserve
    path: "{{ ansible_env.HOME }}/.ssh/config"
    state: touch

- name: Configure client
  ansible.builtin.blockinfile:
    block: |
      # https://carlosbecker.com/posts/ssh-tips-and-tricks/
      Host *
        AddressFamily inet
        ControlMaster auto
        ControlPath /tmp/%r@%h-%p
        ControlPersist 300s
        IdentitiesOnly yes
        ServerAliveCountMax 3
        ServerAliveInterval 30
    marker: "# {mark} global config ANSIBLE MANAGED BLOCK"
    path: "{{ ansible_env.HOME }}/.ssh/config"
