SHELL := /bin/bash
# https://www.gushiciku.cn/pl/p6TH
.SHELLFLAGS := -euo pipefail -c
.ONESHELL:
MAKEFLAGS += --warn-undefined-variables
MAKEFLAGS += --no-builtin-rules

.DEFAULT_GOAL = help

##@ Tests
.PONY: jammy64

jammy64:  ## Run role at ubuntu/jammy64
	vagrant up jammy64 --provision --provision-with test_jammy64.yml

##@ Miscellaneous
.PHONY: clean

clean:  ## Clean repo
	# Delete caches, build artifacts, etc.
	vagrant destroy -f

##@ Helpers
.PHONY: help

help:  ## Display this help
	@awk 'BEGIN {FS = ":.*##"; printf "\nUsage:\n  make \033[36m\033[0m\n"} /^[0-9a-zA-Z_-]+:.*?##/ { printf "  \033[36m%-24s\033[0m %s\n", $$1, $$2 } /^##@/ { printf "\n\033[1m%s\033[0m\n", substr($$0, 5) } ' $(MAKEFILE_LIST)
